name: Update OpenAI Assistant Workflow
on:
  push:
    branches:
      - main

jobs:
  update-assistant:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Update OpenAI Assistant
        uses: ./.github/actions/update_openai_assistant
        with:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
